FROM pathwaycom/pathway:latest

WORKDIR /Task1

COPY . .

CMD echo "--- we are in Docker Container ---" && \
    echo "--- We are in app.py now... ---" && \
    python ./app.py && \
    echo "--- Done.Bye!! ---"